<?php

namespace Lunar\SEO\Modules\General;

use Lunar\SEO\Services\SupportedPostTypes;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Assets {

	// Same instance Module.php boots, so hook_suffix is read from the
	// original add_menu_page() call instead of being guessed again.
	private Admin $admin;

	private SupportedPostTypes $supported_post_types;

	public function __construct( Admin $admin, SupportedPostTypes $supported_post_types ) {
		$this->admin                = $admin;
		$this->supported_post_types = $supported_post_types;
	}

	public function init(): void {
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_admin' ] );
		add_action( 'enqueue_block_editor_assets', [ $this, 'enqueue_editor' ] );
	}

	public function enqueue_admin( string $hook_suffix ): void {
		if ( null === $this->admin->get_hook_suffix() || $hook_suffix !== $this->admin->get_hook_suffix() ) {
			return;
		}

		wp_enqueue_media();

		// @wordpress/scripts outputs a FLAT path (build/admin.js,
		// build/admin.asset.php) for an entry named "admin" in
		// webpack.config.js - not nested (build/admin/index.js). Keep
		// this path matching the entry name exactly.
		$asset_file = LUNAR_SEO_PATH . 'build/admin.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		// Auto-generated by @wordpress/scripts: dependency list plus a
		// content-hash version for cache busting.
		$asset = require $asset_file;

		wp_enqueue_script(
			'lunar-seo-admin',
			LUNAR_SEO_URL . 'build/admin.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		// @wordpress/scripts names the CSS output differently from JS for
		// the same entry - "build/style-admin.css", not "build/admin.css"
		// (MiniCssExtractPlugin prefixes CSS with "style-").
		$style_path = LUNAR_SEO_PATH . 'build/style-admin.css';

		if ( file_exists( $style_path ) ) {
			wp_enqueue_style(
				'lunar-seo-admin',
				LUNAR_SEO_URL . 'build/style-admin.css',
				[],
				$asset['version']
			);
		}
	}

	public function enqueue_editor(): void {
		$screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;

		// Without this guard the Editor bundle would load on every Block
		// Editor screen (attachments, other CPTs, Site Editor/Widgets),
		// even though only supported post types register these meta
		// fields.
		if ( null === $screen || ! $this->supported_post_types->is_supported( $screen->post_type ) ) {
			return;
		}

		$asset_file = LUNAR_SEO_PATH . 'build/editor.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		wp_enqueue_script(
			'lunar-seo-editor',
			LUNAR_SEO_URL . 'build/editor.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		// Same CSS naming pattern as enqueue_admin() above.
		$style_path = LUNAR_SEO_PATH . 'build/style-editor.css';

		if ( file_exists( $style_path ) ) {
			wp_enqueue_style(
				'lunar-seo-editor',
				LUNAR_SEO_URL . 'build/style-editor.css',
				[],
				$asset['version']
			);
		}
	}
}